In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

%matplotlib inline

In [32]:
from sklearn import svm
from sklearn import datasets
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [31]:
#数字データの読み込み
digits = datasets.load_digits()

n = len(digits.data)

1078.2

In [33]:
#画像と正解値の表示
# images = digits.images
# labels = digits.target

# for i in range(10):
#     plt.subplot(2, 5, i+1)
#     plt.imshow(images[i], cmap=plt.cm.gray_r,interpolation="nearest")
#     plt.axis("off")
#     plt.title("Training:" + str(labels[i]))

#サポートベクターマシーン
clf = svm.SVC(gamma=0.001,C=100.0)

X_train,X_test,Y_train,Y_test = train_test_split(digits.data,digits.target)

# #サポートベクターマシーンによる訓練
clf.fit(X_train, Y_train)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [41]:
print(digits.target[-10:])

[5 4 8 8 4 9 0 8 9 8]


In [43]:
print(clf.predict(digits.data[-10:]))

[5 4 8 8 4 9 0 8 9 8]


In [44]:
#予測
predicted = clf.predict(X_test)

#正解率
metrics.accuracy_score(Y_test,predicted)

0.9911111111111112

In [45]:
#誤認識のマトリックス
metrics.confusion_matrix(Y_test,predicted)

array([[50,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 44,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 47,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 54,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 37,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 34,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 43,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 46,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 52,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  1, 39]])